### ISSUE TITLE
Feature request: use ligolo without certificates

### ISSUE THREAD

**Issue by sdcampbell** [tnpitsecurity/ligolo-ng#1]
I'd like to be able to use it on internal pentests or HackTheBox using only IP addresses, no domain names or certificates. This doesn't seem possible. Thanks

**Comment by Nicocha30** [comment]
Hi ! So you mean without TLS ?

**Comment by sdcampbell** [comment]
yes

**Comment by Nicocha30** [comment]
Ok, will do a option to ignore TLS.
On the README, a command is available to generate self signed certificates if you want.

**Comment by Nicocha30** [comment]
Hey @sdcampbell, I implemented in 299077a5123186f8684629665cea315e5a7ab7c8 an option to automatically generate self-signed certificates.

You can run `proxy` with the `-selfcert` option, and the `agent` with the `-ignore-cert` option.

**Comment by sdcampbell** [comment]
Thank you so much! You're awesome!
