### ISSUE TITLE
ConnectEx: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by Atsika** [tnpitsecurity/ligolo-ng#11]
Hi,

There is an error when I try to run agent.exe on a victim machine.

```
C:\Users\ariah\Documents>.\agent.exe -ignore-cert -connect 192.168.49.134:11601
time="2022-01-01T09:42:16-08:00" level=warning msg="warning, certificate validation disabled"
time="2022-01-01T09:42:16-08:00" level=error msg="Connection error: dial tcp 192.168.49.134:11601: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2022-01-01T09:42:16-08:00" level=fatal msg="dial tcp 192.168.49.134:11601: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."

C:\Users\ariah\Documents>
```

This error happened while I was doing **Nickel** from [Proving Grounds](https://portal.offensive-security.com/proving-grounds/practice). I don't know if the error is related to this machine particularly.

Do I need any special right to run the agent ?

Best regards,

Atsika

**Comment by Nicocha30** [comment]
Hi @Atsika , no privileges should be necessary. I will take a look at this issue.

Can you send me some details about the system?

Thanks!

Nicolas.

**Comment by Nicocha30** [comment]
This issue seems to be caused by a firewall policy blocking outbound trafic. Can you confirm and try to change the port?
