### ISSUE TITLE
Include windows version of proxy (server) for windows without TUN

### ISSUE THREAD

**Issue by dennyvsdev** [tnpitsecurity/ligolo-ng#2]
I really would appreciate if you include the windows version of proxy (server) without using TUN like the original ligolo does. I use another software to redirect all traffic to proxy (server) and also TUN isn't available in windows. A TAP driver must be created in windows but i am far from a expert in this field.

**Comment by Nicocha30** [comment]
OK, will look at Wireguard to implement TUN on Windows.

**Comment by dennyvsdev** [comment]
Hey. Any progress? Can you give me a hint of how can I make this work on windows? Maybe i can help too.

**Comment by Nicocha30** [comment]
Hey @dennyvsdev,

I'm working on it, however I'm quite busy and don't have much time to improve ligolo-ng right now. 😕

The goal is to make https://github.com/WireGuard/wireguard-go/blob/master/tun/tun_windows.go compatible with gvisor/netstack.

Fell free to create a pull request if you want 🙂

**Comment by Nicocha30** [comment]
Hey @dennyvsdev , FYI, I'm working on it.

**Comment by Nicocha30** [comment]
Hey @dennyvsdev,

The new Ligolo-ng (0.2) version should work with Windows (https://github.com/tnpitsecurity/ligolo-ng/releases/tag/v0.2). I'm closing this issue!
