### ISSUE TITLE
[FEATURE REQUEST] Please create binary release

### ISSUE THREAD

**Issue by patsevanton** [tnpitsecurity/ligolo-ng#3]
Hello! Thanks for ligolo-ng.
I try add ligolo-ng to https://github.com/devops-works/binenv
But project dont have binary release.
Please create binary release.

**Comment by Nicocha30** [comment]
CI integrated in ddc2e607698ba9d07ee587f647e903e7c07f75e7
Binaries available here: https://github.com/tnpitsecurity/ligolo-ng/releases/tag/v0.1
